#ifndef _GRC_ERROR_CODES_H_
#define _GRC_ERROR_CODES_H_

// ==== function result type ====
#define GRC_OK 0
#define NOT_CLASSIFIED -1
#define I2C_ERROR -2
#define ARGUMENT_ERROR -3
#define WRONG_GRC_ANSWER -4
#define GRC_IS_BUSY -5
#define DATA_NOT_DELIVERED -6
#define NOT_IMPLEMENTED -7
#define SDK_VERSION_MISMATCH -8
#define GRC_GPIO_ERROR -9

#define REMOTE_FUNCTION_ERROR -20
#define REMOTE_FUNCTION_INVAL_STATE -21
#define REMOTE_FUNCTION_INVAL_PARAM -22
#define REMOTE_FUNCTION_INVAL_DATA_LEN -23
#define REMOTE_FUNCTION_NOT_CALLED -24
#define REMOTE_FUNCTION_NOT_IMPLEMENTED -25

#endif //_GRC_ERROR_CODES_H_
